name: autofix
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - ci
    # branches-ignore:
    #   - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run docs
      - run: "git diff --exit-code README.md > /dev/null || echo fail: README.md is outdated, forget to run 'npm run docs'?"
